version: "3.9"
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile-test
    depends_on:
      - server
      - selenium
    environment:
      - TARGET_URL=http://server
      - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
    volumes:
      - "./logs:/app/logs"
  selenium:
    image: selenium/standalone-chrome:89.0
    volumes:
      - "/dev/shm:/dev/shm"
    logging:
      driver: "none"
