FROM node:14-alpine

WORKDIR /app/

COPY ./package.json ./package-lock.json ./
RUN npm ci --only=production && \
  mv ./node_modules/ ./prod_node_modules/ && \
  npm ci

COPY ./tsconfig.json ./
COPY ./src/common/ ./src/common/
