// This file is generated by /src/generate-code.ts
import { InstructionID, InstructionMetadata } from "./instruction";

export const InstructionMetadataList: InstructionMetadata[] = [
  {
    id: InstructionID.JavaScriptBasics,
    name: "初めての JavaScript",
    sections: [
      "JavaScript って何だ？",
      "Hello, World!",
      "コメント",
      "文字列",
      "数値",
      "ブール値",
      "変数",
      "オブジェクト",
      "関数",
      "配列",
      "クラス",
    ],
  },
  {
    id: InstructionID.JavaScriptConditionalOperations,
    name: "JavaScript の条件分岐",
    sections: ["if 文", "switch 文", "Truthy と falsy ？"],
  },
  {
    id: InstructionID.JavaScriptArrayOperations,
    name: "JavaScript の配列",
    sections: [
      "配列に要素を追加",
      "filter",
      "find",
      "map",
      "flat",
      "flatMap",
      "includes",
      "some",
      "every",
      "sort",
      "reduce",
    ],
  },
  {
    id: InstructionID.JavaScriptLoopOperations,
    name: "JavaScript のループ",
    sections: [
      "forEach ループ",
      "while ループ",
      "do while ループ",
      "for ループ",
    ],
  },
  {
    id: InstructionID.HTMLBasics,
    name: "初めての HTML",
    sections: [
      "HTML って何だ？",
      "Hello, World!",
      "要素とタグ",
      "<h1>から<h6>（見出し）",
      "<br>（改行）",
      "<p>（段落）",
      "<a>（リンク）",
      "<ul>と<ol>（リスト）",
      "<img>（画像）",
      "<table>（テーブル）",
      "その他の要素",
    ],
  },
  {
    id: InstructionID.CSSBasics,
    name: "初めての CSS",
    sections: ["CSS って何だ？", "色を変えてみる", "他のプロパティ"],
  },
  {
    id: InstructionID.CSSAsElement,
    name: "要素としての CSS",
    sections: ["<style>（CSS）"],
  },
  {
    id: InstructionID.CSSSelectors,
    name: "CSS セレクタ",
    sections: [
      "要素形セレクタ",
      "クラスセレクタ",
      "ID セレクタ",
      "属性セレクタ",
      "疑似クラス",
      "疑似要素",
      "組み合わせ",
    ],
  },
  {
    id: InstructionID.CSSAsFile,
    name: "ファイルとしての CSS",
    sections: ["<link>（ファイルを読み込む）", "CSS ファイルの中身"],
  },
  {
    id: InstructionID.WebsiteBasics,
    name: "JavaScript と HTML 🧐",
    sections: ["イベント"],
  },
  {
    id: InstructionID.AboutNullToEngineer,
    name: "このサイトについて",
    sections: ["このサイトを作った理由", "ロードマップ", "管理人"],
  },
];
