// This file is generated by /src/generate-code.ts
import { InstructionID, InstructionMetadata } from "./instruction";

export const InstructionMetadataList: InstructionMetadata[] = [
  {
    id: InstructionID.JavaScriptBasics,
    name: "初めての JavaScript",
    sections: [
      "コメント",
      "文字列",
      "数字",
      "ブーリアン（はい・いいえ）",
      "変数",
      "オブジェクト",
      "関数",
      "配列",
    ],
  },
  {
    id: InstructionID.JavaScriptConditionalOperations,
    name: "JavaScript の条件分岐",
    sections: [
      "if 文",
      "switch 文",
      "どんな値が true とみなされて、どんな値が false とみなされるの？",
    ],
  },
  {
    id: InstructionID.JavaScriptArrayOperations,
    name: "JavaScript の配列",
    sections: [
      "配列に要素を追加",
      "filter",
      "find",
      "map",
      "flat",
      "flatMap",
      "includes",
      "some",
      "every",
      "sort",
      "reduce",
    ],
  },
  {
    id: InstructionID.JavaScriptLoopOperations,
    name: "JavaScript のループ",
    sections: [],
  },
];
